const blue = "#1971C2"
const green = "#1e9846"
const grey = "#4b4d52"
const orange = "#de9a33"
const pink = "#ED8998"
const red = "#eb4034"
const white = "white"

export const global = {
  pageSize: 10,
  colors: { blue, green, grey, orange, pink, red },
}

export const config = {
  activity: {
    resourceName: "activity",
    searchFields: ["user.name", "description", "name", "project.name"],
    gauges: {
      main: [
        {
          gaugeName: "gaugeMainResultsCount",
          title: "items",
          color: blue,
          table: "Activity",
        },
      ],
      row: [
        {
          gaugeName: "gaugeFormatPrice",
          title: "Cost",
          priceField: "cost",
          color: green,
        },
      ],
    },
    page: "activities",
    title: "Activities",
    table: {
      name: "Activity",
      sortBy: ["startDate DESC"],
      related: ["customer", "project", "user"],
      tableFields: [
        {
          isIcon: true,
          header: "Edit",
          width: "80px",
          color: white,
        },
        { isDate: true, name: "startDate", header: "Start", width: "12%" },
        { name: "name", header: "Name", width: "20%" },
        { name: "hours", header: "Hours", width: "8%" },
        {
          isAutocomplete: true,
          name: "user",
          header: "User",
          width: "20%",
        },
        {
          isAutocomplete: true,
          name: "project",
          header: "Project",
          width: "20%",
        },
        { name: "description", header: "Description", width: "20%" },
      ],
      formFields: [
        { isDate: true, name: "startDate", header: "Start Date *" },
        { name: "name", header: "Name *" },
        { name: "hours", header: "Hours *" },
        {
          name: "cost",
          header: "Cost",
          hideCreate: true,
          hideUpdate: true,
          dynamic: { api: "/api/activities/cost" },
        },
        {
          isAutocomplete: true,
          name: "customer",
          header: "Customer *",
          page: "customers",
          table: "Customer",
          sortBy: ["name"],
          related: "project",
          relationFilterApi: "/api/relations/findCustomerFromProject",
        },
        {
          isAutocomplete: true,
          name: "project",
          header: "Project *",
          page: "projects",
          table: "Project",
          sortBy: ["name"],
          related: "customer",
          relationFilterApi: "/api/relations/findProjectFromCustomer",
        },
        {
          isAutocomplete: true,
          name: "user",
          header: "User *",
          page: "users",
          table: "User",
          sortBy: ["name"],
        },
        { isNumber: true, name: "extra", header: "Extra cost" },
        { name: "description", header: "Description" },
      ],
    },
  },
  customer: {
    gauges: {
      main: [
        {
          gaugeName: "gaugeMainResultsCount",
          title: "items",
          color: blue,
          table: "Customer",
        },
      ],
      row: [
        {
          gaugeName: "gaugeRowChildrenCount",
          title: "projects",
          color: blue,
          childTable: "Project",
          relationColumn: "customer",
        },
        {
          gaugeName: "gaugeRowChildrenCount",
          title: "activities",
          color: blue,
          childTable: "Activity",
          relationColumn: "customer",
        },
      ],
    },
    page: "customers",
    resourceName: "customer",
    searchFields: [
      "address",
      "addressNumber",
      "cap",
      "city",
      "contactPerson",
      "contactPersonEmail",
      "contactPersonPhone",
      "country",
      "name",
      "phone",
      "vat",
    ],
    table: {
      name: "Customer",
      sortBy: ["name"],
      related: [],
      tableFields: [
        { isIcon: true, header: "Edit", width: "50px", color: white },
        { key: "name", header: "Name", width: "20%" },
        { key: "country", header: "Country", width: "12%" },
        { key: "city", header: "City", width: "12%" },
        { key: "address", header: "Address N.", width: "24%" },
        { key: "vat", header: "VAT-ID", width: "16%" },
        { key: "contactPerson", header: "Contact Person", width: "16%" },
      ],
      formFields: [
        { key: "name", header: "Name *" },
        { key: "country", header: "Country" },
        { key: "city", header: "City" },
        { key: "address", header: "Address" },
        { key: "addressNumber", header: "Address N" },
        { key: "cap", header: "CAP" },
        { key: "phone", header: "Phone" },
        { key: "vat", header: "VAT-ID" },
        { key: "contactPerson", header: "Contact Person" },
        { key: "contactPersonEmail", header: "Contact Person eMail" },
        { key: "contactPersonPhone", header: "Contact Person Phone" },
      ],
    },
    title: "Customers",
  },
  lead: {
    resourceName: "lead",
    searchFields: [
      "customer.name",
      "bid",
      "description",
      "name",
      "status",
      "user.name",
    ],
    gauges: {
      main: [
        {
          gaugeName: "gaugeMainResultsCount",
          title: "items",
          color: blue,
          table: "Project",
        },
        {
          gaugeName: "gaugeMainWhereCounter",
          title: "open",
          color: orange,
          searchFields: ["status"],
          searchString: "open",
        },
        {
          gaugeName: "gaugeMainWhereCounter",
          title: "win",
          color: green,
          searchFields: ["status"],
          searchString: "win",
        },
        {
          gaugeName: "gaugeMainWhereCounter",
          title: "lost",
          color: red,
          searchFields: ["status"],
          searchString: "lost",
        },
        {
          gaugeName: "gaugeRatio",
          title: "win rate",
          color: blue,
          searchFields: ["status"],
          numerator: "win",
          denominator: "lost",
        },
      ],
      row: [],
    },
    page: "leads",
    title: "Leads",
    table: {
      name: "Lead",
      sortBy: ["startDate DESC"],
      related: ["customer", "user"],
      tableFields: [
        { isIcon: true, header: "Edit", width: "50px", color: white },
        {
          isDate: true,
          name: "startDate",
          header: "Creation Date",
          width: "16%",
        },
        {
          isAutocomplete: true,
          name: "customer",
          header: "Customer",
          width: "16%",
        },
        { name: "name", header: "Name", width: "16%" },
        { name: "days", header: "Days", width: "16%" },
        { name: "description", header: "Description", width: "20%" },
        { name: "status", header: "Status", width: "16%" },
      ],
      formFields: [
        { isDate: true, name: "startDate", header: "Creation Date *" },
        { name: "name", header: "Name *" },
        { name: "description", header: "Description" },
        { name: "days", header: "Days *" },
        { isNumber: true, name: "pricing", header: "Pricing *" },
        {
          isAutocomplete: true,
          name: "customer",
          header: "Customer *",
          page: "customers",
          table: "Customer",
          sortBy: ["name"],
        },
        {
          isAutocomplete: true,
          name: "user",
          header: "Owner *",
          page: "users",
          table: "User",
          sortBy: ["name"],
        },
        {
          isSelection: true,
          name: "status",
          header: "Lead Status",
          selection: ["open", "win", "lost"],
          default: "open",
          hideCreate: true,
        },
        { name: "bid", header: "Bid Number" },
      ],
    },
  },
  project: {
    resourceName: "project",
    searchFields: [
      "customer.name",
      "user.name",
      "description",
      "name",
      "status",
    ],
    gauges: {
      main: [
        {
          gaugeName: "gaugeMainResultsCount",
          title: "items",
          color: blue,
          table: "Project",
        },
        {
          gaugeName: "gaugeProjectsGainsLost",
          type: "gain",
          title: "Gains",
          color: green,
        },
        {
          gaugeName: "gaugeProjectsGainsLost",
          type: "lost",
          title: "Lost",
          color: red,
        },
      ],
      row: [
        {
          gaugeName: "gaugeRowChildrenCount",
          title: "activities",
          color: blue,
          childTable: "Activity",
          relationColumn: "project",
        },
        {
          gaugeName: "gaugeRowAggregate",
          title: "total hours",
          color: orange,
          childTable: "Activity",
          relationColumn: "project",
          aggregateField: "hours",
          timeframe: null,
        },
        {
          gaugeName: "gaugeFormatPrice",
          title: "Pricing",
          priceField: "pricing",
          color: green,
        },
        {
          gaugeName: "gaugeAggregateChildrenPrices",
          title: "Cost",
          childTable: "Activity",
          relationColumn: "project",
          aggregateField: "cost",
          color: green,
        },
      ],
    },
    page: "projects",
    title: "Projects",
    table: {
      name: "Project",
      sortBy: ["status DESC", "startDate DESC"],
      related: ["customer", "user"],
      tableFields: [
        { isIcon: true, header: "Edit", width: "50px", color: white },
        { isDate: true, name: "startDate", header: "Start", width: "12%" },
        { name: "name", header: "Name", width: "20%" },
        { name: "days", header: "Days", width: "10%" },
        {
          isDate: true,
          name: "deliveryDate",
          header: "Delivery",
          width: "12%",
        },
        {
          isAutocomplete: true,
          name: "customer",
          header: "Customer",
          width: "16%",
        },
        { name: "description", header: "Description", width: "30%" },
      ],
      formFields: [
        { isDate: true, name: "startDate", header: "Start Date *" },
        { name: "name", header: "Name *" },
        { name: "days", header: "Days *" },
        { isDate: true, name: "deliveryDate", header: "Delivery Date *" },
        { isNumber: true, name: "pricing", header: "Pricing *" },
        {
          isAutocomplete: true,
          name: "customer",
          header: "Customer *",
          page: "customers",
          table: "Customer",
          sortBy: ["name"],
        },
        {
          isAutocomplete: true,
          name: "user",
          header: "Owner *",
          page: "users",
          table: "User",
          sortBy: ["name"],
        },
        { name: "description", header: "Description" },
        {
          isSelection: true,
          name: "status",
          header: "Project Status",
          selection: ["open", "closed"],
          default: "open",
          hideCreate: true,
        },
      ],
    },
  },
  user: {
    resourceName: "user",
    searchFields: [
      "address",
      "contract",
      "email",
      "name",
      "phone",
      "role",
      "skill",
    ],
    gauges: {
      main: [
        {
          gaugeName: "gaugeMainResultsCount",
          title: "items",
          color: blue,
          table: "User",
        },
        {
          gaugeName: "gaugeMainAggregate",
          title: "this month h.",
          color: orange,
          childTable: "Activity",
          aggregateField: "hours",
          timeframe: "currentMonth",
        },
      ],
      row: [
        {
          gaugeName: "gaugeRowChildrenCount",
          title: "activities",
          color: blue,
          childTable: "Activity",
          relationColumn: "user",
        },
        {
          gaugeName: "gaugeRowAggregate",
          title: "this month h.",
          color: orange,
          childTable: "Activity",
          relationColumn: "user",
          aggregateField: "hours",
          timeframe: "currentMonth",
        },
        {
          gaugeName: "gaugeRowAggregate",
          title: "last month h.",
          color: orange,
          childTable: "Activity",
          relationColumn: "user",
          aggregateField: "hours",
          timeframe: "lastMonth",
        },
      ],
    },
    page: "users",
    title: "Users",
    table: {
      name: "User",
      sortBy: "name",
      related: [],
      tableFields: [
        { isIcon: true, header: "Edit", width: "80px", color: white },
        { name: "name", header: "Name", width: "16%" },
        { name: "email", header: "Email", width: "20%" },
        { name: "address", header: "City", width: "16%" },
        { name: "phone", header: "Phone", width: "16%" },
        { name: "skill", header: "Skill", width: "16%" },
        { name: "contract", header: "Contract", width: "16%" },
      ],
      formFields: [
        { name: "name", header: "Name *" },
        { name: "email", header: "Email *" },
        {
          isSelection: true,
          name: "role",
          header: "Role",
          selection: ["admin", "user"],
          default: "user",
        },
        {
          isPassword: true,
          name: "password",
          header: "Password *",
          hideUpdate: true,
        },
        { name: "address", header: "City" },
        { name: "phone", header: "Phone" },
        { name: "skill", header: "Skill" },
        { name: "contract", header: "Contract" },
        { name: "hourlyWage", header: "Hourly Wage *" },
      ],
    },
  },
}
